name: Cache Composer packages
id: composer-cache
uses: actions/cache@v3
with:
  path: vendor
  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
  restore-keys: |
    ${{ runner.os }}-php-