name: 'Cache Composer packages'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ inputs.runner-os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ inputs.runner-os }}-php-